- src/components/App/App.js
- src/components/App/App.test.js
- src/components/App/__snapshots__/App.test.js.snap
- src/components/Navbar/Navbar.css
- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.test.js
- src/components/Navbar/__snapshots__/Navbar.test.js.snap
- src/components/Plugin/Plugin.js
- src/components/Plugins/Plugins.js
- src/components/Router/Router.js
- src/components/Router/Router.test.js
- src/components/Router/__snapshots__/Router.test.js.snap
- src/components/SignIn/SignIn.css
- src/components/SignIn/SignIn.js
- src/components/SignIn/SignIn.test.js
- src/components/SignIn/__snapshots__/SignIn.test.js.snap
- src/components/Welcome/components/WelcomeCTA/WelcomeCTA.css
- src/components/__mocks__/chrisstoreapi.js
- src/components/__mocks__/localStorage.js
- yarn.lock
> Sign In page

- .gitignore
- src/assets/img/not-found.svg
- src/components/NotFound/NotFound.css
- src/components/NotFound/NotFound.js
- src/components/NotFound/NotFound.test.js
- src/components/NotFound/__snapshots__/NotFound.test.js.snap
- src/components/Router/Router.js
- src/components/Router/Router.test.js
- src/components/Router/__snapshots__/Router.test.js.snap
Add 404 page designed by Shania. Add route logic, image, tests and snapshot.
> Add 404 Page not found for invalid page routes.

- package-lock.json
- package.json
- src/components/CreatePlugin/CreatePlugin.js
- src/components/Developers/components/DeveloperCTA/__snapshots__/DeveloperCTA.test.js.snap
- src/components/Developers/components/DeveloperSignup/DeveloperSignup.css
- src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
- src/components/Developers/components/DeveloperSignup/DeveloperSignup.test.js
- src/components/Developers/components/DeveloperSignup/__snapshots__/DeveloperSignup.test.js.snap
- src/components/Plugin/Plugin.js
- src/components/Plugins/Plugins.js
- src/components/SignIn/SignIn.js
- src/components/__mocks__/chrisstoreapi.js
- yarn.lock
1. update the chris api version to latest.
2. fix incompatibility issues with chris store api across the ui.
3. add password confirm to form (need to add email to future or is username also email?)
4. validate form for missing items and non matching passwords (need to do more validation in the future ?)
5. send form data down to store using store api
6. fetch auth token to validate create user was successful.
7. update tests
**UPDATED WITH EMAIL FORM ITEM**
> Add Developer Signup functionality. 

- src/components/CreatePlugin/CreatePlugin.css
- src/components/CreatePlugin/CreatePlugin.js
- src/components/Dashboard/Dashboard.js
- src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.js
Add delete plugin to the developer dashboard.
> Add delete to dashboard

- src/components/App/App.js
- src/components/CreatePlugin/CreatePlugin.js
- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.test.js
- src/components/Navbar/__snapshots__/Navbar.test.js.snap
- src/components/Router/Router.js
- src/components/Router/Router.test.js
- src/components/SignIn/SignIn.js
- src/components/SignIn/SignIn.test.js
- src/components/SignIn/__snapshots__/SignIn.test.js.snap
Fix the failing unit tests and update ci to a green state.
> Fix unit tests

- src/components/CreatePlugin/CreatePlugin.js
A pull request from a non-master branch to accommodated a suggestion made by @jcaianirh
> Issue18 Pull request

- src/components/Dashboard/Dashboard.js
- src/components/Developers/Developers.js
- src/components/Developers/Developers.test.js
- src/components/Developers/__snapshots__/Developers.test.js.snap
- src/components/Developers/components/DeveloperCTA/DeveloperCTA.js
- src/components/Developers/components/DeveloperCTA/DeveloperCTA.test.js
- src/components/Developers/components/DeveloperCTA/__snapshots__/DeveloperCTA.test.js.snap
- src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
- src/components/Developers/components/DeveloperSignup/DeveloperSignup.test.js
- src/components/Developers/components/DeveloperSignup/__snapshots__/DeveloperSignup.test.js.snap
- src/store/ChrisEffects.js
Address issue: https://github.com/FNNDSC/ChRIS_store_ui/issues/35
Update create user flow so new user doesn't have to log in after creating account. Flow shown in video:
1. developer page with signup form visible
2. pending successful signup redirect to dashboard page
3. navigating to developer page shows same page without form.
4. logout
> Update create user flow

- src/components/Dashboard/Dashboard.js
PR for #50 
- Increased the "limit" to 20. 
- This follows the standard set in Plugins.js implementation
> Increased limit size for getPlugin 

- package.json
- src/components/CreatePlugin/CreatePlugin.js
- src/components/Dashboard/Dashboard.js
- src/components/Plugin/Plugin.js
- src/components/Plugins/Plugins.js
- yarn.lock
This also updates ChRIS store API calls. A few mock tests fail. But they should be easy for you to fix :)
@jcaianirh @gagansk
> Update ChRIS store JS client to v1.1.5

- src/components/Plugin/Plugin.test.js
- src/components/__mocks__/chrisstoreapi.js
Fix: https://github.com/FNNDSC/ChRIS_store_ui/issues/58
update return values for successful test completion.
> fix breaking tests for api v1.1.5

- package.json
- src/components/CreatePlugin/CreatePlugin.js
- src/components/Dashboard/Dashboard.js
- src/components/Plugin/Plugin.js
- src/components/Plugin/Plugin.test.js
- src/components/Plugins/Plugins.js
- src/components/__mocks__/chrisstoreapi.js
- yarn.lock
Create a conditional statement to handle the errors at the time of creation of plugin gracefully.
Current implementation: As of now, the entire response received from the server is begin rendered as it is in the UI.
Expected implementation: Display the reason for failing in creating the plugin.
Eg: A plugin with the given name already exists. or The URL format for the repo is not valid.
> Graceful handling of Failure of Plugin Creation 

- package-lock.json
- src/components/Router/NewApp.js
- src/components/Router/ProtectedRoute.js
- src/components/Router/Router.js
- src/components/Router/Router.test.js
- src/components/Router/__snapshots__/Router.test.js.snap
This PR contains 
- Protected Route to Dashboard and Create pages. Only logged in users will be able to see these two pages.
- Modification in test to accommodate the changes.
> Private Route for Dashboard and Create

- src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
This PR has validation for the creation of users in store based on the server response.
> Server side validation of User creation

- src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.js
Fixing the issue of text overflow in the edit box committed in the previous pull request
> Fix text overflow

- .gitignore
- src/components/Plugin/Plugin.js
- src/components/Plugin/Plugin.test.js
https://github.com/FNNDSC/ChRIS_store_ui/issues/70
> Removed v text from the plugin version .

- src/components/CreatePlugin/CreatePlugin.test.js
- src/components/__mocks__/chrisstoreapi.js
jbernal0019 I have fixed test which i have marked as skip in the yesterday PR - https://github.com/FNNDSC/ChRIS_store_ui/pull/82
> Fixed failed test .

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.test.js
- src/components/Navbar/__snapshots__/Navbar.test.js.snap
- src/components/Router/Router.js
- src/components/Router/__snapshots__/Router.test.js.snap
- src/components/SignIn/SignIn.js
- src/components/SignIn/__snapshots__/SignIn.test.js.snap
https://github.com/FNNDSC/ChRIS_store_ui/issues/34
Renamed Developer route to Quick Start
> Change Developer nav to Quick Start .

- src/components/Plugin/Plugin.css
- src/components/Plugin/Plugin.js
- src/components/Plugin/components/PluginBody/PluginBody.css
- src/components/Plugin/components/PluginBody/PluginBody.js
- src/components/Plugin/components/PluginBody/PluginBody.test.js
Update the Plugins details page to match the latest designs.
> fixes https://github.com/FNNDSC/ChRIS_store_ui/issues/86
> Update Plugin Details UI

- src/components/App/__snapshots__/App.test.js.snap
- src/components/Plugin/Plugin.test.js
- src/components/Plugin/__snapshots__/Plugin.test.js.snap
- src/components/Plugin/components/PluginBody/PluginBody.js
- src/components/Plugin/components/PluginBody/PluginBody.test.js
- src/components/Router/__snapshots__/Router.test.js.snap
I have skipped the unit test cases because we are changing the plugin body component and we also need to change in the future to integrate with the backend.
We will fix these test case when we integrate with the backend.
> skip test cases for plugin .

- src/components/App/App.js
- src/components/general/ScrollToTop.js
Fixes: #14 
- Added a component ScrollToTop to restore the page scroll position on page change.
> Page scroll restoration implemented 

- src/components/Footer/Footer.css
- src/components/Footer/Footer.js
- src/components/Footer/Footer.test.js
Solves issue #98 
- Added necessary links to the footer.
- Made current year dynamic.
> footer fixes

- src/components/Plugin/components/PluginBody/PluginBody.js
Fixes issue #71 
Added Plugin ID to display.
> Plugin fix

- src/components/App/App.js
- src/components/CreatePlugin/CreatePlugin.js
- src/components/CreatePlugin/CreatePlugin.test.js
- src/components/general/ScrollToTop.js
Fixes: #113 
1) Created an Alert warning component.
> Showing warning when Docker image ends with ":latest"

- src/components/Plugin/Plugin.js
Fixes: [#129](https://github.com/FNNDSC/ChRIS_store_ui/issues/129)
@jennydaman please review this. I have fixed the placeholder text on chrisstore.co/create.
> fix: placeholder text on chrisstore.co/create

- package.json
- src/components/Navbar/Navbar.js
- src/components/Navbar/components/Search/Search.css
- src/components/Navbar/components/Search/Search.js
- yarn.lock
Enhancement: #101 
1. Implemented a configurable search component
2. Brought search component to the horizontal nav in smaller screens
3. Changed functionality of search icon: User can click on the icon to search
> Search Component enhancement and Fix for small screens

- src/components/Plugins/Plugins.js
> Search query fix

- src/components/Button/index.js
- src/components/SignIn/SignIn.js
1) Added type props.
2) Used arrow function to stop immediate function call in toRoute props.
> Button: bug fix 

- src/components/AppLayout/AppLayout.js
- src/components/AppLayout/applayout.css
- src/components/Navbar/Navbar.css
- src/components/Navbar/Navbar.js
- src/components/Navbar/components/Search/Search.css
- src/components/Navbar/components/Search/Search.js
- src/components/Plugins/Plugins.js
- src/components/SignIn/SignIn.js
- src/utils/common.js
Fixes: #146 
1) Implemented autocomplete component.
2) Changed search bar position for screens below 768px.
3) Used debounce in search.
> Autocomplete Search pf4

- src/components/Dashboard/Dashboard.js
- src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.js
- src/components/Notification/Notifications.css
- src/components/Notification/index.js
- src/components/Plugin/Plugin.js
- src/components/Plugins/Plugins.js
- src/errors/HttpApiCallError.js
Fixes: #13 and #101 
1) Created a reuseable notification component in patternfly-4 to display the error messages.
> UI Notifications for errors

- src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
- src/components/FormInput/index.js
- src/components/SignIn/SignIn.js
Fixes: #101 
1) Implemented FormInput component to be used throughout the project
@jennydaman please review the styling of the forms as currently we have the default styling of patternfly4
> Form pf3 to pf4

- package.json
- src/components/Developers/__snapshots__/Developers.test.js.snap
- src/components/Developers/components/DeveloperCTA/__snapshots__/DeveloperCTA.test.js.snap
- src/components/Developers/components/DeveloperSignup/__snapshots__/DeveloperSignup.test.js.snap
- src/components/Footer/__snapshots__/Footer.test.js.snap
- src/components/Notification/index.js
- src/components/Plugin/Plugin.css
- src/components/Plugin/Plugin.js
- src/components/Plugin/__snapshots__/Plugin.test.js.snap
- src/components/Plugin/components/PluginBody/PluginBody.css
- src/components/Plugin/components/PluginBody/PluginBody.js
- src/components/Plugins/Plugins.js
- src/components/Plugins/__snapshots__/Plugins.test.js.snap
- src/components/Plugins/components/PluginItem/PluginItem.js
- src/components/Plugins/components/PluginsCategories/__snapshots__/PluginsCategories.test.js.snap
- src/components/SignIn/__snapshots__/SignIn.test.js.snap
- src/components/Welcome/__snapshots__/Welcome.test.js.snap
- src/components/Welcome/components/WelcomeCategories/__snapshots__/WelcomeCategories.test.js.snap
- src/components/Welcome/components/WelcomeChRIS/__snapshots__/WelcomeChRIS.test.js.snap
- src/components/Welcome/components/WelcomeDevelopers/__snapshots__/WelcomeDevelopers.test.js.snap
- yarn.lock
These fixes focus on making the Plugin component more relevant and useable.
1. Fetching repository data from Github public API to use for populating relevant fields.
2. Fetch README from public repo community profile from Github public API to display as plugin documentation.
3. Display README as Markdown using package [marked](https://www.npmjs.com/package/marked).
4. Fixed many layout issues in PluginBody and made the component slightly more mobile friendly.
With further discussion more changes will be added according to what direction is to be taken. 
This is not the final state of this work.
> Updated plugin body

- src/components/CreatePlugin/CreatePlugin.js
- src/components/SignIn/SignIn.js
Fixes: #101
1) Upgraded Alert component from pf3 to pf4.
> Alert upgradation from pf3 to pf4

- src/components/Navbar/components/Search/Search.css
- src/components/Navbar/components/Search/Search.js
- src/hooks/useKeyPressHook.js
Fixes: #170 
1) Made a custom hook (useKeyPress hook) 
2) User can use the up and down key to select a particular item from the autocomplete list and can use enter key to search it.
@jennydaman please review and let me know the required changes.
> Arrow key functionality in AutoComplete

- src/components/Plugin/components/PluginBody/PluginBody.js
- src/components/general/CopyURLButton.js
Fixes issue #101 
- Changed the icons to pf4
- Changed the component to functional component
> Plugin copy-url-btn

- src/components/Plugin/Plugin.js
fixes #181 Added dynamic favorited-by count so that it can be fetched from the db
> removed hardcoded favorited by count in plugin component

- src/components/Dashboard/Dashboard.css
- src/components/Dashboard/Dashboard.js
Fixes: #101 
1) Upgraded spinner component from pf3 to pf4 in Dashboard.js
2) Removed pf3 component CardGrid.
> spinner upgraded

- src/components/Plugin/PluginMeta.jsx
- src/components/Plugin/components/PluginBody/PluginBody.jsx
@zrthxn This PR lists plugin collaborators on the PluginMeta inittial fix for #245
> fetch PluginMeta Collaborators'

- src/components/Plugins/Plugins.jsx
> Fix bug plugin count in search results

- README.md
Fixes #278
Added quotation to the path.
> Refactored docker run command

- .eslintrc
- package.json
- yarn.lock
Enforced the use of single quotes
After:
> Fix: Single quote rule is not enforced 

- src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> Fix: Plugin dropdown menu gets cut off on mobile
